// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/lab" | "/admin/lab/voice" | "/app" | "/app/discover" | "/app/explore" | "/app/onboarding" | "/app/settings" | "/app/settings/billing" | "/docs/explicacoes" | "/docs/html/readme" | "/explore" | "/faq" | "/forgot-password" | "/login" | "/pricing" | "/privacy" | "/profile" | "/register" | "/reset-password" | "/support" | "/terms" | "/u/[username]" | "/u/[username]/p/[postId]"
type AppRouteHandlerRoutes = "/api/admin/curator-ingest" | "/api/admin/lab/backfill-intros" | "/api/admin/lab/queue" | "/api/admin/lab/tts" | "/api/admin/metrics" | "/api/admin/qubic-backfill-images" | "/api/admin/qubic-ingest" | "/api/admin/x-sync" | "/api/ai/verify-post" | "/api/billing/ai/checkout" | "/api/billing/checkout" | "/api/billing/library/checkout" | "/api/billing/portal" | "/api/cron/curator-ingest" | "/api/cron/qubic-x-ingest" | "/api/cron/x-listening-sync" | "/api/curator/card" | "/api/library/tts" | "/api/listening/queue" | "/api/listening/tts" | "/api/moderate-image" | "/api/presence/heartbeat" | "/api/profiles/search" | "/api/recommended-reading/search" | "/api/recommended-reading/source" | "/api/webhooks/stripe" | "/api/x/sync" | "/auth/callback" | "/icons/icon-192" | "/icons/icon-512"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/admin/lab" | "/app" | "/app/explore" | "/app/settings" | "/profile" | "/u"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/lab": {}
  "/admin/lab/voice": {}
  "/api/admin/curator-ingest": {}
  "/api/admin/lab/backfill-intros": {}
  "/api/admin/lab/queue": {}
  "/api/admin/lab/tts": {}
  "/api/admin/metrics": {}
  "/api/admin/qubic-backfill-images": {}
  "/api/admin/qubic-ingest": {}
  "/api/admin/x-sync": {}
  "/api/ai/verify-post": {}
  "/api/billing/ai/checkout": {}
  "/api/billing/checkout": {}
  "/api/billing/library/checkout": {}
  "/api/billing/portal": {}
  "/api/cron/curator-ingest": {}
  "/api/cron/qubic-x-ingest": {}
  "/api/cron/x-listening-sync": {}
  "/api/curator/card": {}
  "/api/library/tts": {}
  "/api/listening/queue": {}
  "/api/listening/tts": {}
  "/api/moderate-image": {}
  "/api/presence/heartbeat": {}
  "/api/profiles/search": {}
  "/api/recommended-reading/search": {}
  "/api/recommended-reading/source": {}
  "/api/webhooks/stripe": {}
  "/api/x/sync": {}
  "/app": {}
  "/app/discover": {}
  "/app/explore": {}
  "/app/onboarding": {}
  "/app/settings": {}
  "/app/settings/billing": {}
  "/auth/callback": {}
  "/docs/explicacoes": {}
  "/docs/html/readme": {}
  "/explore": {}
  "/faq": {}
  "/forgot-password": {}
  "/icons/icon-192": {}
  "/icons/icon-512": {}
  "/login": {}
  "/pricing": {}
  "/privacy": {}
  "/profile": {}
  "/register": {}
  "/reset-password": {}
  "/support": {}
  "/terms": {}
  "/u": {}
  "/u/[username]": { "username": string; }
  "/u/[username]/p/[postId]": { "username": string; "postId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/admin/lab": never
  "/app": never
  "/app/explore": never
  "/app/settings": never
  "/profile": never
  "/u": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
