// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/explore/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/explore">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/explore/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/u/[username]/p/[postId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/u/[username]/p/[postId]">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/u/[username]/p/[postId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/u/[username]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/u/[username]">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/u/[username]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/lab">> = Specific
  const handler = {} as typeof import("../../src/app/admin/lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/lab/voice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/lab/voice">> = Specific
  const handler = {} as typeof import("../../src/app/admin/lab/voice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(audiopost)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/(audiopost)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(standard)/discover/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/discover">> = Specific
  const handler = {} as typeof import("../../src/app/app/(standard)/discover/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(standard)/explore/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/explore">> = Specific
  const handler = {} as typeof import("../../src/app/app/(standard)/explore/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(standard)/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/app/(standard)/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(standard)/settings/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/settings/billing">> = Specific
  const handler = {} as typeof import("../../src/app/app/(standard)/settings/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(standard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/settings">> = Specific
  const handler = {} as typeof import("../../src/app/app/(standard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/docs/explicacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/explicacoes">> = Specific
  const handler = {} as typeof import("../../src/app/docs/explicacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/docs/html/readme/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/html/readme">> = Specific
  const handler = {} as typeof import("../../src/app/docs/html/readme/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/curator-ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/curator-ingest">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/curator-ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/lab/backfill-intros/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/lab/backfill-intros">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/lab/backfill-intros/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/lab/queue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/lab/queue">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/lab/queue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/lab/tts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/lab/tts">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/lab/tts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/metrics">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/qubic-backfill-images/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/qubic-backfill-images">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/qubic-backfill-images/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/qubic-ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/qubic-ingest">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/qubic-ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/x-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/x-sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/x-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/verify-post/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/verify-post">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/verify-post/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/ai/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/ai/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/ai/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/library/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/library/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/library/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/portal">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/curator-ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/curator-ingest">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/curator-ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/qubic-x-ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/qubic-x-ingest">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/qubic-x-ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/x-listening-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/x-listening-sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/x-listening-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/curator/card/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/curator/card">> = Specific
  const handler = {} as typeof import("../../src/app/api/curator/card/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/library/tts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/library/tts">> = Specific
  const handler = {} as typeof import("../../src/app/api/library/tts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/listening/queue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/listening/queue">> = Specific
  const handler = {} as typeof import("../../src/app/api/listening/queue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/listening/tts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/listening/tts">> = Specific
  const handler = {} as typeof import("../../src/app/api/listening/tts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/moderate-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moderate-image">> = Specific
  const handler = {} as typeof import("../../src/app/api/moderate-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/presence/heartbeat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/presence/heartbeat">> = Specific
  const handler = {} as typeof import("../../src/app/api/presence/heartbeat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profiles/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/profiles/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recommended-reading/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recommended-reading/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/recommended-reading/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recommended-reading/source/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recommended-reading/source">> = Specific
  const handler = {} as typeof import("../../src/app/api/recommended-reading/source/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/x/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/x/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/x/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/icons/icon-192/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/icons/icon-192">> = Specific
  const handler = {} as typeof import("../../src/app/icons/icon-192/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/icons/icon-512/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/icons/icon-512">> = Specific
  const handler = {} as typeof import("../../src/app/icons/icon-512/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/u/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/u">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/u/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/lab/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/lab">> = Specific
  const handler = {} as typeof import("../../src/app/admin/lab/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(audiopost)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/(audiopost)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(standard)/explore/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/explore">> = Specific
  const handler = {} as typeof import("../../src/app/app/(standard)/explore/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(standard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/(standard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(standard)/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/settings">> = Specific
  const handler = {} as typeof import("../../src/app/app/(standard)/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
